name: Actions Workflows

on: [push]

jobs:
  run-git-hub-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple javascript actions
        id: simple_javacript_action
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: sreenivas
      - name: List Files
        run: |
          pwd
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo "${{ github.token }}"
          git clone git@github.com:$GITHUB_REPOSITORY.git
          git checkout $GITHUB_SHA
          ls -l

      - name: Log output of javascript Action
        run: echo "${{ steps.simple_javacript_action.outputs.time }}"  
      - name: Checkout brightcove Repo
        uses: actions/checkout@v3
        with:
          ref: 1.1.x
          token: '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'
          path: brightcove
          repository: sreenivasulu-paruchuri/brightcove_dynamic_ingest 
      - name: List File
        run: |
          pwd
          cd brightcove
          ls -a   
      - name: Checkout Current Repo
        uses: actions/checkout@v3
        with:
          ref: main
          token: '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'
          path: github_actions
      - name: List File
        run: |
          pwd
          cd github_actions
          ls -a    
        