name: Actions Workflows

on: [push]

jobs:
  run-git-hub-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple javascript actions
        id: simple_javacript_action
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: sreenivas
      - name: Log output of javascript Action
        run: echo "${{ steps.simple_javacript_action.outputs.time }}"  
      - name: Checkout brightcove Repo
        uses: actions/checkout@v3
        with:
          ref: 1.1.x
          path: brightcove
          repository: sreenivasulu-paruchuri/brightcove_dynamic_ingest 
      - name: List File
        run: |
          pwd
          ls -al    
      - name: Checkout Current Repo
        uses: actions/checkout@v3
        with:
          ref: main
          path: github_actions
      - name: List File
        run: |
          pwd
          ls -al     
        