name: Shell Commands

on: push

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "First Git Hub Actions Command"
            - name: multiline script
              run: |
                node -v
                npm -v  
            - name: current Directory
              run: pwd    
            - name: php version
              run: php -v  
    
    run-windows-commands:
        runs-on: windows-latest
        steps:
            - name: Current windows Directory
              run: pwd
              shell: bash